spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    chain.strategy.content.enabled: true
    chain.strategy.content.paths: /**

  # jackson 相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write_numbers_as_strings: true

  #http 相关配置
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  profiles:
    active: dev

# mybatis 相关配置
mybatis:
  mapper-locations: classpath*:/mapper/**.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  configuration:
    lazyLoadingEnabled: false #延时加载的开关
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: com.mdd.admin.config.mybatisplus.MddStdOutImpl
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
server:
  port: 8083

login:
  #aes 加密key
  aes.key: 1234567812345678
  #登录时长 单位S
  time: 3600
  # 单实例登录
  owner: true

xxl:
  job:
    admin:
      address: http://122.51.238.59:9980/xxl-job-admin
    executor:
      appname: mdd-job-executor
      ip:
      port: 9999
      accessToken:
      logpath: e:/xxllog/
      logretentiondays: -1