spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    chain.strategy.content.enabled: true
    chain.strategy.content.paths: /**

  #redis相关配置
  redis:
    database: 2 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 2000ms  # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2  # 连接池中的最小空闲连接

  # jackson 相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write_numbers_as_strings: true

  #http 相关配置
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  #数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  #ʹ使用 Hikari连接池
    driver-class-name: com.mysql.jdbc.Driver  #mysql驱动
    url: jdbc:mysql://localhost:3306/bootdemo?useSSL=false
    username: root
    password: 888888
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

# mybatis 相关配置
mybatis:
  mapper-locations: classpath*:/mapper/**.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  configuration:
    lazyLoadingEnabled: false #延时加载的开关
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: com.mdd.admin.config.mybatisplus.MddStdOutImpl
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
server:
  port: 8081

login:
  #aes 加密key
  aes.key: 1234567812345678
  #登录时长 单位S
  time: 3600
  # 单实例登录
  owner: true
